-- CBoard metadata (from sql/mysql/mysql.sql + extensions)
CREATE TABLE dashboard_user (
    user_id         VARCHAR(50)  NOT NULL PRIMARY KEY,
    login_name      VARCHAR(100),
    user_name       VARCHAR(100),
    user_password   VARCHAR(255),
    user_status     VARCHAR(100),
    business_code   VARCHAR(50)
);

CREATE TABLE dashboard_role (
    role_id   VARCHAR(100) NOT NULL PRIMARY KEY,
    role_name VARCHAR(100),
    user_id   VARCHAR(50)
);

CREATE TABLE dashboard_user_role (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(100),
    role_id      VARCHAR(100)
);

CREATE TABLE dashboard_role_res (
    role_res_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     VARCHAR(100),
    res_type    VARCHAR(100),
    res_id      BIGINT,
    permission  VARCHAR(20)
);

CREATE TABLE dashboard_category (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    user_id       VARCHAR(100) NOT NULL
);

CREATE TABLE dashboard_board (
    board_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(50)  NOT NULL,
    category_id BIGINT,
    board_name  VARCHAR(100) NOT NULL,
    layout_json CLOB,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dashboard_datasource (
    datasource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(50)  NOT NULL,
    source_name   VARCHAR(100) NOT NULL,
    source_type   VARCHAR(100) NOT NULL,
    config        CLOB,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dashboard_widget (
    widget_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(100) NOT NULL,
    category_name VARCHAR(100),
    widget_name   VARCHAR(100),
    data_json     CLOB,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dashboard_dataset (
    dataset_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(100) NOT NULL,
    category_name VARCHAR(100),
    dataset_name  VARCHAR(100),
    data_json     CLOB,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dashboard_job (
    job_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name       VARCHAR(200),
    cron_exp       VARCHAR(200),
    start_date     TIMESTAMP,
    end_date       TIMESTAMP,
    job_type       VARCHAR(200),
    job_config     CLOB,
    user_id        VARCHAR(100),
    last_exec_time TIMESTAMP,
    job_status     BIGINT,
    exec_log       CLOB
);

CREATE TABLE dashboard_board_param (
    board_param_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        VARCHAR(50) NOT NULL,
    board_id       BIGINT      NOT NULL,
    config         CLOB
);
