-- Combined schema: CBoard metadata + analytics (H2, PostgreSQL-compatible mode)
CREATE TABLE IF NOT EXISTS dashboard_user (
    user_id         VARCHAR(50)  NOT NULL PRIMARY KEY,
    login_name      VARCHAR(100),
    user_name       VARCHAR(100),
    user_password   VARCHAR(255),
    user_status     VARCHAR(100),
    business_code   VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS dashboard_role (
    role_id   VARCHAR(100) NOT NULL PRIMARY KEY,
    role_name VARCHAR(100),
    user_id   VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS dashboard_user_role (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(100),
    role_id      VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS dashboard_role_res (
    role_res_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     VARCHAR(100),
    res_type    VARCHAR(100),
    res_id      BIGINT,
    permission  VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS dashboard_category (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    user_id       VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dashboard_board (
    board_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(50)  NOT NULL,
    category_id BIGINT,
    board_name  VARCHAR(100) NOT NULL,
    layout_json CLOB,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dashboard_datasource (
    datasource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(50)  NOT NULL,
    source_name   VARCHAR(100) NOT NULL,
    source_type   VARCHAR(100) NOT NULL,
    config        CLOB,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dashboard_widget (
    widget_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(100) NOT NULL,
    category_name VARCHAR(100),
    widget_name   VARCHAR(100),
    data_json     CLOB,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dashboard_dataset (
    dataset_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(100) NOT NULL,
    category_name VARCHAR(100),
    dataset_name  VARCHAR(100),
    data_json     CLOB,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dashboard_job (
    job_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name       VARCHAR(200),
    cron_exp       VARCHAR(200),
    start_date     TIMESTAMP,
    end_date       TIMESTAMP,
    job_type       VARCHAR(200),
    job_config     CLOB,
    user_id        VARCHAR(100),
    last_exec_time TIMESTAMP,
    job_status     BIGINT,
    exec_log       CLOB
);

CREATE TABLE IF NOT EXISTS dashboard_board_param (
    board_param_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        VARCHAR(50) NOT NULL,
    board_id       BIGINT      NOT NULL,
    config         CLOB
);

CREATE TABLE IF NOT EXISTS category_std_info (
    category_code  VARCHAR(20) PRIMARY KEY,
    channel        VARCHAR(100),
    site           VARCHAR(200),
    business_code  VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS daily_kwd_trend_cnt_minimal_v2 (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fid             VARCHAR(50),
    business_code   VARCHAR(50),
    category_code   VARCHAR(20),
    doc_date        DATE NOT NULL,
    kwd_a           VARCHAR(200) NOT NULL,
    kwd_b           VARCHAR(200),
    doc_cnt_a       INT DEFAULT 0,
    doc_cnt_b       INT DEFAULT 0,
    doc_cnt_both    INT DEFAULT 0,
    pos_cnt_both    INT DEFAULT 0,
    neg_cnt_both    INT DEFAULT 0,
    neu_cnt_both    INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS daily_stock_data (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fid          VARCHAR(50),
    trade_date   DATE NOT NULL,
    open_price   DECIMAL(18,4),
    high_price   DECIMAL(18,4),
    low_price    DECIMAL(18,4),
    close_price  DECIMAL(18,4),
    volume       BIGINT
);

CREATE TABLE IF NOT EXISTS script_rel_docs_std_info (
    script_uid    VARCHAR(100) PRIMARY KEY,
    fid           VARCHAR(50),
    category_code VARCHAR(20),
    business_code VARCHAR(50),
    script_title  VARCHAR(500),
    script_rank   INT,
    script_date   DATE,
    job_id        VARCHAR(50)
);
