spring:
  application:
    name: katsulabs-bi
  lifecycle:
    timeout-per-shutdown-phase: 5s
  flyway:
    enabled: true
    locations: classpath:db/migration

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081
  shutdown: graceful
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        same-site: lax
        http-only: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
