-- Simplified analytics mart for local H2 (PostgreSQL dm/std compatible names)

CREATE TABLE category_std_info (
    category_code  VARCHAR(20) PRIMARY KEY,
    channel        VARCHAR(100),
    site           VARCHAR(200),
    business_code  VARCHAR(50)
);

CREATE TABLE daily_kwd_trend_cnt_minimal_v2 (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fid             VARCHAR(50),
    business_code   VARCHAR(50),
    category_code   VARCHAR(20),
    doc_date        DATE NOT NULL,
    kwd_a           VARCHAR(200) NOT NULL,
    kwd_b           VARCHAR(200),
    doc_cnt_a       INT DEFAULT 0,
    doc_cnt_b       INT DEFAULT 0,
    doc_cnt_both    INT DEFAULT 0,
    pos_cnt_both    INT DEFAULT 0,
    neg_cnt_both    INT DEFAULT 0,
    neu_cnt_both    INT DEFAULT 0
);

CREATE TABLE daily_stock_data (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fid          VARCHAR(50),
    trade_date   DATE NOT NULL,
    open_price   DECIMAL(18,4),
    high_price   DECIMAL(18,4),
    low_price    DECIMAL(18,4),
    close_price  DECIMAL(18,4),
    volume       BIGINT
);

CREATE TABLE script_rel_docs_std_info (
    script_uid    VARCHAR(100) PRIMARY KEY,
    fid           VARCHAR(50),
    category_code VARCHAR(20),
    business_code VARCHAR(50),
    script_title  VARCHAR(500),
    script_rank   INT,
    script_date   DATE,
    job_id        VARCHAR(50)
);

-- Seed: admin uses BCrypt in V3
INSERT INTO category_std_info (category_code, channel, site, business_code) VALUES
('BDPC01', 'news', 'example.com', 'FIN');

INSERT INTO daily_kwd_trend_cnt_minimal_v2
(fid, business_code, category_code, doc_date, kwd_a, kwd_b, doc_cnt_a, doc_cnt_b, doc_cnt_both, pos_cnt_both, neg_cnt_both, neu_cnt_both)
VALUES
('BDPC04030205', 'FIN', 'BDPC01', CURRENT_DATE - 2, '코스피', '상승', 10, 8, 15, 10, 3, 2),
('BDPC04030205', 'FIN', 'BDPC01', CURRENT_DATE - 1, '코스피', '변동성', 12, 6, 18, 8, 5, 5),
('BDPC04030205', 'FIN', 'BDPC01', CURRENT_DATE, '금리', '한국은행', 20, 15, 25, 12, 4, 9);

INSERT INTO daily_stock_data (fid, trade_date, open_price, high_price, low_price, close_price, volume)
VALUES
('BDPC04030205', CURRENT_DATE - 1, 2500, 2550, 2480, 2530, 1000000),
('BDPC04030205', CURRENT_DATE, 2530, 2580, 2520, 2565, 1200000);

INSERT INTO script_rel_docs_std_info (script_uid, fid, category_code, business_code, script_title, script_rank, script_date)
VALUES
('S001', 'BDPC04030205', 'BDPC01', 'FIN', '시장 브리핑 요약', 1, CURRENT_DATE);
