-- Schema v2: dashboard_* 제거, ib_* 정규화 메타 스키마
-- 기존 DB는 파괴적 마이그레이션 (데모·로컬 H2 전제)

DROP TABLE IF EXISTS dashboard_board_param;
DROP TABLE IF EXISTS dashboard_board;
DROP TABLE IF EXISTS dashboard_widget;
DROP TABLE IF EXISTS dashboard_dataset;
DROP TABLE IF EXISTS dashboard_datasource;
DROP TABLE IF EXISTS dashboard_category;
DROP TABLE IF EXISTS dashboard_user_role;
DROP TABLE IF EXISTS dashboard_role_res;
DROP TABLE IF EXISTS dashboard_job;
DROP TABLE IF EXISTS dashboard_user;
DROP TABLE IF EXISTS dashboard_role;

DROP TABLE IF EXISTS ib_board_filter_option;
DROP TABLE IF EXISTS ib_board_filter;
DROP TABLE IF EXISTS ib_board_widget;
DROP TABLE IF EXISTS ib_board;
DROP TABLE IF EXISTS ib_widget_binding;
DROP TABLE IF EXISTS ib_widget;
DROP TABLE IF EXISTS ib_dataset_column;
DROP TABLE IF EXISTS ib_dataset;
DROP TABLE IF EXISTS ib_datasource;
DROP TABLE IF EXISTS ib_category;
DROP TABLE IF EXISTS ib_user_role;
DROP TABLE IF EXISTS ib_user;
DROP TABLE IF EXISTS ib_role;

-- ─── RBAC ───
CREATE TABLE ib_role (
    role_id     VARCHAR(20)  NOT NULL PRIMARY KEY,
    role_name   VARCHAR(100) NOT NULL
);

CREATE TABLE ib_user (
    user_id           VARCHAR(50)  NOT NULL PRIMARY KEY,
    login_name        VARCHAR(100) NOT NULL,
    user_name         VARCHAR(100),
    password_hash     VARCHAR(128) NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    default_board_id  BIGINT,
    created_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ib_user_role (
    user_id VARCHAR(50) NOT NULL PRIMARY KEY,
    role_id VARCHAR(20) NOT NULL
);

-- ─── 카테고리 (보드·위젯·데이터셋 공통 트리) ───
CREATE TABLE ib_category (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    owner_user_id VARCHAR(50)  NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ─── DataSource ───
CREATE TABLE ib_datasource (
    datasource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    type          VARCHAR(50)  NOT NULL,
    owner_user_id VARCHAR(50)  NOT NULL,
    config_json   CLOB         NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ─── Dataset ───
CREATE TABLE ib_dataset (
    dataset_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datasource_id    BIGINT       NOT NULL,
    category_id      BIGINT,
    name             VARCHAR(100) NOT NULL,
    owner_user_id    VARCHAR(50)  NOT NULL,
    sql_text         CLOB         NOT NULL,
    platform_shared  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ib_dataset_column (
    column_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id   BIGINT       NOT NULL,
    column_name  VARCHAR(200) NOT NULL,
    kind         VARCHAR(20)  NOT NULL,
    alias        VARCHAR(200),
    sort_order   INT NOT NULL DEFAULT 0
);

-- ─── Widget ───
CREATE TABLE ib_widget (
    widget_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id    BIGINT       NOT NULL,
    category_id   BIGINT,
    name          VARCHAR(100) NOT NULL,
    owner_user_id VARCHAR(50)  NOT NULL,
    chart_type    VARCHAR(50)  NOT NULL,
    options_json  CLOB,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ib_widget_binding (
    binding_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    widget_id    BIGINT       NOT NULL,
    axis         VARCHAR(20)  NOT NULL,
    column_name  VARCHAR(200) NOT NULL,
    alias        VARCHAR(200),
    aggregate_fn VARCHAR(50),
    sort_order   INT NOT NULL DEFAULT 0
);

-- ─── Board ───
CREATE TABLE ib_board (
    board_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id           BIGINT,
    name                  VARCHAR(100) NOT NULL,
    owner_user_id         VARCHAR(50)  NOT NULL,
    layout_mode           VARCHAR(20)  NOT NULL DEFAULT 'GRID',
    layout_json           CLOB,
    published_to_viewers  BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at          TIMESTAMP,
    published_by          VARCHAR(50),
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ib_board_widget (
    board_id      BIGINT NOT NULL,
    widget_id     BIGINT NOT NULL,
    row_index     INT    NOT NULL DEFAULT 0,
    column_index  INT    NOT NULL DEFAULT 0,
    width_cols    INT    NOT NULL DEFAULT 12,
    height_px     INT,
    pos_x         INT,
    pos_y         INT,
    pos_ex        INT,
    pos_ey        INT,
    sort_order    INT    NOT NULL DEFAULT 0,
    PRIMARY KEY (board_id, widget_id)
);

CREATE TABLE ib_board_filter (
    filter_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id      BIGINT       NOT NULL,
    column_name   VARCHAR(200) NOT NULL,
    label         VARCHAR(200),
    default_value VARCHAR(500),
    sort_order    INT NOT NULL DEFAULT 0
);

CREATE TABLE ib_board_filter_option (
    filter_id    BIGINT       NOT NULL,
    option_value VARCHAR(500) NOT NULL,
    PRIMARY KEY (filter_id, option_value)
);

CREATE INDEX idx_ib_dataset_datasource ON ib_dataset (datasource_id);
CREATE INDEX idx_ib_widget_dataset ON ib_widget (dataset_id);
CREATE INDEX idx_ib_board_published ON ib_board (published_to_viewers);
CREATE INDEX idx_ib_board_widget_board ON ib_board_widget (board_id);

-- ─── 시드: 역할·사용자 (비밀번호 admin123 SHA-256 HEX) ───
INSERT INTO ib_role (role_id, role_name) VALUES
    ('1', 'Super Admin'),
    ('2', 'Viewer'),
    ('3', 'Manager');

INSERT INTO ib_user (user_id, login_name, user_name, password_hash, status) VALUES
    ('admin01', 'admin01', 'Admin', '240BE518FABD2724DDB6F04EEB1DA5967448D7E831C08C8FA822809F74C720A9', 'ACTIVE'),
    ('manager01', 'manager01', 'Manager User', '240BE518FABD2724DDB6F04EEB1DA5967448D7E831C08C8FA822809F74C720A9', 'ACTIVE'),
    ('viewer01', 'viewer01', 'Viewer User', '240BE518FABD2724DDB6F04EEB1DA5967448D7E831C08C8FA822809F74C720A9', 'ACTIVE');

INSERT INTO ib_user_role (user_id, role_id) VALUES
    ('admin01', '1'),
    ('manager01', '3'),
    ('viewer01', '2');

INSERT INTO ib_category (name, owner_user_id) VALUES
    ('Demo', 'admin01'),
    ('Data Source Samples', 'admin01'),
    ('Default Category', 'admin01');

-- demo_source (H2 in-memory — V3와 동일)
INSERT INTO ib_datasource (name, type, owner_user_id, config_json) VALUES (
    'demo_source',
    'jdbc',
    'admin01',
    '{"aggregateProvider":true,"password":"","pooled":true,"driver":"org.h2.Driver","jdbcurl":"jdbc:h2:mem:insight-board;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE","username":"sa"}'
);

INSERT INTO ib_dataset (datasource_id, category_id, name, owner_user_id, sql_text, platform_shared)
SELECT
    ds.datasource_id,
    (SELECT category_id FROM ib_category WHERE name = 'Default Category' AND owner_user_id = 'admin01'),
    'foodmart_sample',
    'admin01',
    'SELECT * FROM sales_fact_sample_flat',
    TRUE
  FROM ib_datasource ds
 WHERE ds.name = 'demo_source';

INSERT INTO ib_dataset_column (dataset_id, column_name, kind, alias, sort_order)
SELECT d.dataset_id, 'the_year', 'DIMENSION', 'the_year', 1
  FROM ib_dataset d WHERE d.name = 'foodmart_sample';
INSERT INTO ib_dataset_column (dataset_id, column_name, kind, alias, sort_order)
SELECT d.dataset_id, 'SALES_COUNTRY', 'DIMENSION', 'SALES_COUNTRY', 2
  FROM ib_dataset d WHERE d.name = 'foodmart_sample';
INSERT INTO ib_dataset_column (dataset_id, column_name, kind, alias, sort_order)
SELECT d.dataset_id, 'store_sales', 'MEASURE', 'store_sales', 3
  FROM ib_dataset d WHERE d.name = 'foodmart_sample';
INSERT INTO ib_dataset_column (dataset_id, column_name, kind, alias, sort_order)
SELECT d.dataset_id, 'store_cost', 'MEASURE', 'store_cost', 4
  FROM ib_dataset d WHERE d.name = 'foodmart_sample';

-- Widget: fm_price_line (line)
INSERT INTO ib_widget (dataset_id, category_id, name, owner_user_id, chart_type)
SELECT
    d.dataset_id,
    (SELECT category_id FROM ib_category WHERE name = 'Data Source Samples' AND owner_user_id = 'admin01'),
    'fm_price_line',
    'admin01',
    'line'
  FROM ib_dataset d WHERE d.name = 'foodmart_sample';

INSERT INTO ib_widget_binding (widget_id, axis, column_name, alias, aggregate_fn, sort_order)
SELECT w.widget_id, 'ROW', 'the_year', 'the_year', NULL, 1
  FROM ib_widget w WHERE w.name = 'fm_price_line';
INSERT INTO ib_widget_binding (widget_id, axis, column_name, alias, aggregate_fn, sort_order)
SELECT w.widget_id, 'VALUE', 'store_sales', 'store_sales', 'sum', 1
  FROM ib_widget w WHERE w.name = 'fm_price_line';

-- Widget: fm_country_pie (pie)
INSERT INTO ib_widget (dataset_id, category_id, name, owner_user_id, chart_type)
SELECT
    d.dataset_id,
    (SELECT category_id FROM ib_category WHERE name = 'Data Source Samples' AND owner_user_id = 'admin01'),
    'fm_country_pie',
    'admin01',
    'pie'
  FROM ib_dataset d WHERE d.name = 'foodmart_sample';

INSERT INTO ib_widget_binding (widget_id, axis, column_name, alias, aggregate_fn, sort_order)
SELECT w.widget_id, 'ROW', 'SALES_COUNTRY', 'SALES_COUNTRY', NULL, 1
  FROM ib_widget w WHERE w.name = 'fm_country_pie';
INSERT INTO ib_widget_binding (widget_id, axis, column_name, alias, aggregate_fn, sort_order)
SELECT w.widget_id, 'VALUE', 'store_sales', 'store_sales', 'sum', 1
  FROM ib_widget w WHERE w.name = 'fm_country_pie';

-- Board: FoodMart Sample (게시 + 연도 파라미터)
INSERT INTO ib_board (category_id, name, owner_user_id, layout_mode, layout_json, published_to_viewers, published_by, published_at)
SELECT
    c.category_id,
    'FoodMart Sample Dashboard',
    'admin01',
    'GRID',
    NULL,
    TRUE,
    'admin01',
    CURRENT_TIMESTAMP
  FROM ib_category c
 WHERE c.name = 'Data Source Samples' AND c.owner_user_id = 'admin01';

UPDATE ib_board
   SET layout_json =
    '{"type":"grid","rows":[{"type":"param","params":[{"col":"the_year","label":"연도","values":["2016","2017"],"defaultValue":"2016"}]},{"type":"widget","height":"320","widgets":['
    || '{"widgetId":' || (SELECT CAST(w1.widget_id AS VARCHAR) FROM ib_widget w1 WHERE w1.name = 'fm_price_line')
    || ',"name":"fm_price_line","width":6},'
    || '{"widgetId":' || (SELECT CAST(w2.widget_id AS VARCHAR) FROM ib_widget w2 WHERE w2.name = 'fm_country_pie')
    || ',"name":"fm_country_pie","width":6}'
    || ']}]}'
 WHERE name = 'FoodMart Sample Dashboard';

INSERT INTO ib_board_widget (board_id, widget_id, row_index, column_index, width_cols, sort_order)
SELECT b.board_id, w.widget_id, 1, 0, 6, 1
  FROM ib_board b, ib_widget w
 WHERE b.name = 'FoodMart Sample Dashboard' AND w.name = 'fm_price_line';

INSERT INTO ib_board_widget (board_id, widget_id, row_index, column_index, width_cols, sort_order)
SELECT b.board_id, w.widget_id, 1, 1, 6, 2
  FROM ib_board b, ib_widget w
 WHERE b.name = 'FoodMart Sample Dashboard' AND w.name = 'fm_country_pie';

INSERT INTO ib_board_filter (board_id, column_name, label, default_value, sort_order)
SELECT board_id, 'the_year', '연도', '2016', 1
  FROM ib_board WHERE name = 'FoodMart Sample Dashboard';

INSERT INTO ib_board_filter_option (filter_id, option_value)
SELECT f.filter_id, '2016'
  FROM ib_board_filter f
  JOIN ib_board b ON b.board_id = f.board_id
 WHERE b.name = 'FoodMart Sample Dashboard' AND f.column_name = 'the_year';

INSERT INTO ib_board_filter_option (filter_id, option_value)
SELECT f.filter_id, '2017'
  FROM ib_board_filter f
  JOIN ib_board b ON b.board_id = f.board_id
 WHERE b.name = 'FoodMart Sample Dashboard' AND f.column_name = 'the_year';

-- Viewer 기본 홈 보드
UPDATE ib_user u
   SET default_board_id = (SELECT board_id FROM ib_board WHERE name = 'FoodMart Sample Dashboard')
 WHERE u.user_id = 'viewer01';

-- Demo Board (미게시, admin 작업용)
INSERT INTO ib_board (category_id, name, owner_user_id, layout_mode, layout_json, published_to_viewers)
SELECT
    c.category_id,
    'Demo Board',
    'admin01',
    'GRID',
    '{"type":"grid","rows":[{"type":"widget","height":"320","widgets":[]}]}',
    FALSE
  FROM ib_category c
 WHERE c.name = 'Demo' AND c.owner_user_id = 'admin01';

-- ─── 부동산·경제 데모 (V7 물리 테이블 + ib_* 메타) ───
INSERT INTO ib_category (name, owner_user_id)
SELECT 'Demo Data', 'admin01'
 WHERE NOT EXISTS (SELECT 1 FROM ib_category WHERE name = 'Demo Data' AND owner_user_id = 'admin01');

INSERT INTO ib_datasource (name, type, owner_user_id, config_json)
SELECT 'demo_realestate', 'jdbc', 'admin01',
  '{"aggregateProvider":true,"password":"","pooled":true,"driver":"org.h2.Driver","jdbcurl":"jdbc:h2:mem:insight-board;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE","username":"sa"}'
 WHERE NOT EXISTS (SELECT 1 FROM ib_datasource WHERE name = 'demo_realestate');

INSERT INTO ib_datasource (name, type, owner_user_id, config_json)
SELECT 'demo_economic', 'jdbc', 'admin01',
  '{"aggregateProvider":true,"password":"","pooled":true,"driver":"org.h2.Driver","jdbcurl":"jdbc:h2:mem:insight-board;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE","username":"sa"}'
 WHERE NOT EXISTS (SELECT 1 FROM ib_datasource WHERE name = 'demo_economic');

INSERT INTO ib_dataset (datasource_id, category_id, name, owner_user_id, sql_text, platform_shared)
SELECT ds.datasource_id,
       (SELECT category_id FROM ib_category WHERE name = 'Demo Data' AND owner_user_id = 'admin01'),
       'realestate_korea', 'admin01',
       'SELECT deal_year, deal_quarter, city, district, property_type, avg_price_100m, transaction_count, avg_area_sqm FROM real_estate_sample',
       TRUE
  FROM ib_datasource ds WHERE ds.name = 'demo_realestate'
   AND NOT EXISTS (SELECT 1 FROM ib_dataset WHERE name = 'realestate_korea');

INSERT INTO ib_dataset_column (dataset_id, column_name, kind, sort_order)
SELECT d.dataset_id, col.column_name, col.kind, col.sort_order
  FROM ib_dataset d
 CROSS JOIN (
    VALUES ('deal_year', 'DIMENSION', 1), ('city', 'DIMENSION', 2), ('district', 'DIMENSION', 3),
           ('property_type', 'DIMENSION', 4), ('avg_price_100m', 'MEASURE', 5),
           ('transaction_count', 'MEASURE', 6), ('avg_area_sqm', 'MEASURE', 7)
  ) AS col(column_name, kind, sort_order)
 WHERE d.name = 'realestate_korea'
   AND NOT EXISTS (SELECT 1 FROM ib_dataset_column c WHERE c.dataset_id = d.dataset_id);

INSERT INTO ib_dataset (datasource_id, category_id, name, owner_user_id, sql_text, platform_shared)
SELECT ds.datasource_id,
       (SELECT category_id FROM ib_category WHERE name = 'Demo Data' AND owner_user_id = 'admin01'),
       'economic_indicators', 'admin01',
       'SELECT indicator_year, indicator_month, country, indicator_code, indicator_name, indicator_value, unit FROM economic_indicator_sample',
       TRUE
  FROM ib_datasource ds WHERE ds.name = 'demo_economic'
   AND NOT EXISTS (SELECT 1 FROM ib_dataset WHERE name = 'economic_indicators');

INSERT INTO ib_dataset_column (dataset_id, column_name, kind, sort_order)
SELECT d.dataset_id, col.column_name, col.kind, col.sort_order
  FROM ib_dataset d
 CROSS JOIN (
    VALUES ('indicator_year', 'DIMENSION', 1), ('indicator_month', 'DIMENSION', 2),
           ('country', 'DIMENSION', 3), ('indicator_name', 'DIMENSION', 4),
           ('indicator_value', 'MEASURE', 5)
  ) AS col(column_name, kind, sort_order)
 WHERE d.name = 'economic_indicators'
   AND NOT EXISTS (SELECT 1 FROM ib_dataset_column c WHERE c.dataset_id = d.dataset_id);

-- Chart Gallery (demo_line — aggregate reload 테스트용)
INSERT INTO ib_widget (dataset_id, category_id, name, owner_user_id, chart_type)
SELECT d.dataset_id,
       (SELECT category_id FROM ib_category WHERE name = 'Demo' AND owner_user_id = 'admin01'),
       'demo_line', 'admin01', 'line'
  FROM ib_dataset d WHERE d.name = 'foodmart_sample'
   AND NOT EXISTS (SELECT 1 FROM ib_widget WHERE name = 'demo_line');

INSERT INTO ib_widget_binding (widget_id, axis, column_name, alias, aggregate_fn, sort_order)
SELECT w.widget_id, 'ROW', 'the_year', 'the_year', NULL, 1
  FROM ib_widget w WHERE w.name = 'demo_line'
   AND NOT EXISTS (SELECT 1 FROM ib_widget_binding b WHERE b.widget_id = w.widget_id);

INSERT INTO ib_widget_binding (widget_id, axis, column_name, alias, aggregate_fn, sort_order)
SELECT w.widget_id, 'VALUE', 'store_sales', 'store_sales', 'sum', 2
  FROM ib_widget w WHERE w.name = 'demo_line'
   AND EXISTS (SELECT 1 FROM ib_widget_binding b WHERE b.widget_id = w.widget_id AND b.sort_order = 1)
   AND NOT EXISTS (SELECT 1 FROM ib_widget_binding b WHERE b.widget_id = w.widget_id AND b.sort_order = 2);

INSERT INTO ib_board (category_id, name, owner_user_id, layout_mode, layout_json, published_to_viewers)
SELECT c.category_id, 'Chart Gallery', 'admin01', 'GRID',
       '{"type":"grid","rows":[{"type":"widget","height":"400","widgets":[]}]}', FALSE
  FROM ib_category c
 WHERE c.name = 'Demo' AND c.owner_user_id = 'admin01'
   AND NOT EXISTS (SELECT 1 FROM ib_board WHERE name = 'Chart Gallery');

INSERT INTO ib_board (category_id, name, owner_user_id, layout_mode, layout_json, published_to_viewers)
SELECT c.category_id, 'Real Estate Sample Dashboard', 'admin01', 'GRID',
       '{"type":"grid","rows":[{"type":"widget","height":"320","widgets":[]}]}', FALSE
  FROM ib_category c
 WHERE c.name = 'Data Source Samples' AND c.owner_user_id = 'admin01'
   AND NOT EXISTS (SELECT 1 FROM ib_board WHERE name = 'Real Estate Sample Dashboard');

INSERT INTO ib_board (category_id, name, owner_user_id, layout_mode, layout_json, published_to_viewers)
SELECT c.category_id, 'Economic Indicators Sample Dashboard', 'admin01', 'GRID',
       '{"type":"grid","rows":[{"type":"widget","height":"320","widgets":[]}]}', FALSE
  FROM ib_category c
 WHERE c.name = 'Data Source Samples' AND c.owner_user_id = 'admin01'
   AND NOT EXISTS (SELECT 1 FROM ib_board WHERE name = 'Economic Indicators Sample Dashboard');
